### ISSUE TITLE
Username on URL

### ISSUE THREAD

**Issue by AlissonEnz** [markthethomas/isbusy#3]
Hi Mark,

It's not an issue, but it'd be great if the user could choose a username and use it on the URL, like Instagram, Facebook, Github, and so on.

E.g.: Currently my isBusy URL is https://isbusy.app/s/l3NUxKJWE but I use the nickname **alissonenz** everywhere, so it'd be much easier if my URL became https://isbusy.app/s/alissonenz

BTW, great project.

**Comment by markthethomas** [comment]
@AlissonEnz interesting! I can definitely get that in place! I had thought about that originally but wasn't sure if there would be demand :)

**Comment by markthethomas** [comment]
@AlissonEnz tracking here: https://github.com/markthethomas/isbusy/projects/1#card-41028267

**Comment by markthethomas** [comment]
hey @AlissonEnz I added custom URL support! Let me know if you have any other ideas! 
<img width="1643" alt="Screen Shot 2020-06-30 at 1 43 07 PM" src="https://user-images.githubusercontent.com/4926721/86175307-ef13ab00-bad7-11ea-8861-13d3539a52e1.png">

**Comment by AlissonEnz** [comment]
Wow cool 👏 

After I changed it, when I clicked on the navigation button "my status page" it sent me to the old id page.
But then I refreshed the page and worked perfectly.

**Comment by markthethomas** [comment]
Ah! I think the UI must not be respecting the update - I’ll fix that, too!
