### ISSUE TITLE
Received an error when refreshing page after linking google calendar

### ISSUE THREAD

**Issue by maximgeller** [markthethomas/isbusy#5]
![image](https://user-images.githubusercontent.com/57017700/87937112-110ea680-ca62-11ea-8d7e-c06e1bc6b3b8.png)

Using brave browser on my iPhone, I got this error when I refreshed the profile page after linking my google calendar

**Comment by markthethomas** [comment]
hey! weird - can you try removing it from isBusy and from your google account? once that's done, you should be able to re-add back to isBusy and that should work

**Comment by maximgeller** [comment]
Seems to be working now, but I added it from my computer this time so I don't know if that would make a difference

**Comment by markthethomas** [comment]
Hmm. Device won’t matter, but depends on what google account you were signed into. Glad it works though!
