### ISSUE TITLE
Failed to handle signup webhook

### ISSUE THREAD

**Issue by mariobustosjmz** [markthethomas/isbusy#6]
Error: `Failed to handle signup webhook`   , I can't Sing Up.

---

![Screenshot from 2021-02-11 13-45-24](https://user-images.githubusercontent.com/8094321/107691426-0a9b8280-6c71-11eb-9921-5e95dc2633b3.png)

**Comment by markthethomas** [comment]
hey sorry about this - there was a busted redis server not responding. all should work now!
