### ISSUE TITLE
Not able to create an account, 

### ISSUE THREAD

**Issue by TejasCreative** [markthethomas/isbusy#7]
Whenever I attempt to create an account, I get an error stating: Failed to handle signup webhook across multiple browsers

**Comment by markthethomas** [comment]
hey sorry about this - there was a busted redis server not responding. all should work now!

**Comment by TejasCreative** [comment]
Ah thank you so much!

**Comment by TMShader** [comment]
I'd like to reopen this, since I'm getting the same error.
